-- Supabase schema for Project Knowledge
-- Paste this into the Supabase SQL editor and run it.

create extension if not exists vector;
create extension if not exists pgcrypto;

-- Profiles table (optional but recommended for auth integration)
create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    username text not null,
    email text not null,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

alter table public.profiles enable row level security;

create policy if not exists "Users can view own profile" on public.profiles
    for select using (auth.uid() = id);

create policy if not exists "Users can update own profile" on public.profiles
    for update using (auth.uid() = id);

create policy if not exists "Users can insert own profile" on public.profiles
    for insert with check (auth.uid() = id);

-- User details
create table if not exists public.user_details (
    id bigint generated by default as identity primary key,
    name text,
    mobile_number text,
    email_id text,
    github_url text,
    linkedin_url text,
    portfolio_link text,
    location text,
    profession_summary text,
    user_uuid uuid not null references auth.users(id) on delete cascade,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

alter table public.user_details enable row level security;

create policy if not exists "Users can manage own user details" on public.user_details
    for all using (auth.uid() = user_uuid) with check (auth.uid() = user_uuid);

-- Education
create table if not exists public.education (
    id bigint generated by default as identity primary key,
    course_name text not null,
    cgpa double precision,
    start_year integer,
    end_year integer,
    college_name text,
    location text,
    user_uuid uuid not null references auth.users(id) on delete cascade,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

alter table public.education enable row level security;

create policy if not exists "Users can manage own education" on public.education
    for all using (auth.uid() = user_uuid) with check (auth.uid() = user_uuid);

-- Certificates
create table if not exists public.certificates (
    id bigint generated by default as identity primary key,
    certificate_issuer text,
    certificate_name text not null,
    user_uuid uuid not null references auth.users(id) on delete cascade,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

alter table public.certificates enable row level security;

create policy if not exists "Users can manage own certificates" on public.certificates
    for all using (auth.uid() = user_uuid) with check (auth.uid() = user_uuid);

-- Internship
create table if not exists public.internship (
    id bigint generated by default as identity primary key,
    company_name text not null,
    role text,
    description text,
    duration text,
    user_uuid uuid not null references auth.users(id) on delete cascade,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

alter table public.internship enable row level security;

create policy if not exists "Users can manage own internship" on public.internship
    for all using (auth.uid() = user_uuid) with check (auth.uid() = user_uuid);

-- Achievements
create table if not exists public.achievements (
    id bigint generated by default as identity primary key,
    description text not null,
    user_uuid uuid not null references auth.users(id) on delete cascade,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

alter table public.achievements enable row level security;

create policy if not exists "Users can manage own achievements" on public.achievements
    for all using (auth.uid() = user_uuid) with check (auth.uid() = user_uuid);

-- Projects
create table if not exists public.projects (
    id bigint generated by default as identity primary key,
    name text not null,
    description text,
    tech_stack text,
    github_url text,
    live_link text,
    user_uuid uuid not null references auth.users(id) on delete cascade,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

alter table public.projects enable row level security;

create policy if not exists "Users can manage own projects" on public.projects
    for all using (auth.uid() = user_uuid) with check (auth.uid() = user_uuid);

-- Skills
create table if not exists public.skills (
    id bigint generated by default as identity primary key,
    name text not null,
    description text,
    user_uuid uuid not null references auth.users(id) on delete cascade,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

alter table public.skills enable row level security;

create policy if not exists "Users can manage own skills" on public.skills
    for all using (auth.uid() = user_uuid) with check (auth.uid() = user_uuid);

-- Document embeddings
create table if not exists public.document_embeddings (
    id bigint generated by default as identity primary key,
    user_uuid uuid not null references auth.users(id) on delete cascade,
    source_table text not null,
    source_id bigint not null,
    content text not null,
    embedding vector(384),
    created_at timestamptz default now()
);

alter table public.document_embeddings enable row level security;

create policy if not exists "Users can manage own embeddings" on public.document_embeddings
    for all using (auth.uid() = user_uuid) with check (auth.uid() = user_uuid);

-- Helpful indexes
create index if not exists idx_user_details_user_uuid on public.user_details(user_uuid);
create index if not exists idx_education_user_uuid on public.education(user_uuid);
create index if not exists idx_certificates_user_uuid on public.certificates(user_uuid);
create index if not exists idx_internship_user_uuid on public.internship(user_uuid);
create index if not exists idx_achievements_user_uuid on public.achievements(user_uuid);
create index if not exists idx_projects_user_uuid on public.projects(user_uuid);
create index if not exists idx_skills_user_uuid on public.skills(user_uuid);
create index if not exists idx_document_embeddings_user_uuid on public.document_embeddings(user_uuid);
